name: CI

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  convert-to-draft:
    name: Convert PR to Draft
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Move Pull Request to Draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr ready "$PR_URL" --undo
